### ISSUE TITLE
[PE-D][Tester B] bug: alphanumeric student name permitted in command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T16-4/tp#132]
### Description
- Typically, a normal person's name should only contain alphabets. Currently, TutorTrack permits name to be alphanumeric.

### Steps to reproduce
- Run `add n/John Poe 1 p/84920491 e/poe@yuh.com a/RVRC s/Physics`

### Expected
- Reject user command

### Actual
- Person with alphanumeric name is created

### Screenshots
![image.png](https://raw.githubusercontent.com/ForAeons/ped/main/files/46e27ceb-e778-4c96-a735-deaab8b94a88.png)

### Remarks
- Note that this issue is based on [release v1.3](https://github.com/AY2324S2-CS2103T-T16-4/tp/releases/tag/v1.3) as v1.3.1 cannot launch on my system. The issues found is based on v1.3 release as instructed by prof

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ForAeons/ped#13

**Comment by HusseinSafwan02** [comment]
specify names can be alphanumeric in UG
